#!/bin/bash
# Merge all mp3-files in current directory using ffmpeg
# 
# Usage:
# mp3-merge-files

if [ "0" -eq $(sudo find . -type f -iname "*.mp3" | wc -l ) ]; then
    echo -e "\e[31m\e[48;5;235mNo .mp3 files found.\e[0m"
    exit
fi

FILES=$(s=""; for i in *.mp3; do s="$s|$i"; done; echo ${s:1})

ffmpeg -i "concat:$FILES" -acodec copy output.mp3
